name: Publish

on:
  push

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: rc
      - name: Publish to JSR
        run: deno publish
